services:
  - type: web
    name: django-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: your-very-secret-key
      - key: ALLOWED_HOSTS
        value: your-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString

databases:
  - name: your-db-name
    databaseName: your-db-name
    user: your-db-user
